project:
  type: website
  resources: static
  output-dir: docs

website:
  title: "Zach Budesa, The Website"
  site-url: "zbudesa.com"
  twitter-card: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projs.qmd
      - text: CV
        href: static/cv.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




