project:
  type: website
  resources: static
  output-dir: docs

website:
  title: "Zach Budesa, PhD"
  twitter-card: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




